### ISSUE TITLE
tried it and it crashed

### ISSUE THREAD

**Issue by sgehrman** [hoomanmmd/fade_out_particle#1]
![image](https://user-images.githubusercontent.com/287137/174286323-3afa9384-402e-439f-b382-bd2aa75f2368.png)

**Comment by hoomanmmd** [comment]
Thanks for filling the issue.
can you include your code and also flutter doctor output

**Comment by hoomanmmd** [comment]
Thanks for filling the issue. @sgehrman 
can you include your code and also flutter doctor output
